services:
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
  cards:
    build:
      context: .
      dockerfile: cards/Dockerfile
  collection:
    build:
      context: .
      dockerfile: collection/Dockerfile
  proxy:
    image: nginx:1-alpine
    ports:
        - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth
      - cards
      - collection