services:
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
  cards:
    build:
      context: .
      dockerfile: cards/Dockerfile
  collection:
    build:
      context: .
      dockerfile: collection/Dockerfile
  proxy:
    build:
      context: nginx
    ports:
        - "8080:80"
    depends_on:
      - auth
      - cards
      - collection