on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            path:
              - ${{ inputs.name }}/**
              - build.gradle.kts
              - gradle
      - name: Log in to the Container registry
        if: steps.filter.outputs.path == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        if: steps.filter.outputs.path == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{inputs.name}}
      - name: Download Jars
        if: steps.filter.outputs.path == 'true'
        uses: actions/download-artifact@v4
        with:
          name: jars
      - name: Build and push Docker images
        id: push
        if: steps.filter.outputs.path == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        if: steps.filter.outputs.path == 'true'
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/${{inputs.name}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true