name: Build & publish docker images
on:
  push:
    tags:
      - '*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./auth/Dockerfile
            image: ghcr.io/projet-app-cloud-dev/auth
            name: auth
          - dockerfile: ./cards/Dockerfile
            image: ghcr.io/projet-app-cloud-dev/cards
            name: cards
          - dockerfile: ./collection/Dockerfile
            image: ghcr.io/projet-app-cloud-dev/collection
            name: collection
          - dockerfile: ./nginx/Dockerfile
            image: ghcr.io/projet-app-cloud-dev/proxy
            name: proxy
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/${{matrix.name}}-(.+)$ ]]; then
            echo "tag=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "match=true" >> $GITHUB_OUTPUT
          fi
      - name: Checkout repository
        uses: actions/checkout@v2
        if: steps.check-tag.outputs.match == 'true'
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.check-tag.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
